/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common';

export interface RewardsManagerInterface extends utils.Interface {
  functions: {
    'ajnaToken()': FunctionFragment;
    'calculateRewards(uint256,uint256)': FunctionFragment;
    'claimRewards(uint256,uint256,uint256)': FunctionFragment;
    'emergencyUnstake(uint256)': FunctionFragment;
    'getBucketStateStakeInfo(uint256,uint256)': FunctionFragment;
    'getStakeInfo(uint256)': FunctionFragment;
    'isBucketUpdated(address,uint256,uint256)': FunctionFragment;
    'isEpochClaimed(uint256,uint256)': FunctionFragment;
    'positionManager()': FunctionFragment;
    'rewardsClaimed(uint256)': FunctionFragment;
    'stake(uint256)': FunctionFragment;
    'unstake(uint256)': FunctionFragment;
    'updateBucketExchangeRatesAndClaim(address,bytes32,uint256[])': FunctionFragment;
    'updateRewardsClaimed(uint256)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'ajnaToken'
      | 'calculateRewards'
      | 'claimRewards'
      | 'emergencyUnstake'
      | 'getBucketStateStakeInfo'
      | 'getStakeInfo'
      | 'isBucketUpdated'
      | 'isEpochClaimed'
      | 'positionManager'
      | 'rewardsClaimed'
      | 'stake'
      | 'unstake'
      | 'updateBucketExchangeRatesAndClaim'
      | 'updateRewardsClaimed'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'ajnaToken', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'calculateRewards',
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: 'claimRewards',
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'emergencyUnstake', values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'getBucketStateStakeInfo',
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'getStakeInfo', values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'isBucketUpdated',
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: 'isEpochClaimed',
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'positionManager', values?: undefined): string;
  encodeFunctionData(functionFragment: 'rewardsClaimed', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'unstake', values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'updateBucketExchangeRatesAndClaim',
    values: [string, BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: 'updateRewardsClaimed', values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: 'ajnaToken', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'calculateRewards', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'claimRewards', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'emergencyUnstake', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getBucketStateStakeInfo', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getStakeInfo', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isBucketUpdated', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isEpochClaimed', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'positionManager', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'rewardsClaimed', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'unstake', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'updateBucketExchangeRatesAndClaim',
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: 'updateRewardsClaimed', data: BytesLike): Result;

  events: {
    'ClaimRewards(address,address,uint256,uint256[],uint256)': EventFragment;
    'MoveStakedLiquidity(uint256,uint256[],uint256[])': EventFragment;
    'Stake(address,address,uint256)': EventFragment;
    'Unstake(address,address,uint256)': EventFragment;
    'UpdateExchangeRates(address,address,uint256[],uint256)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'ClaimRewards'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'MoveStakedLiquidity'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Stake'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Unstake'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'UpdateExchangeRates'): EventFragment;
}

export interface ClaimRewardsEventObject {
  owner: string;
  ajnaPool: string;
  tokenId: BigNumber;
  epochsClaimed: BigNumber[];
  amount: BigNumber;
}
export type ClaimRewardsEvent = TypedEvent<
  [string, string, BigNumber, BigNumber[], BigNumber],
  ClaimRewardsEventObject
>;

export type ClaimRewardsEventFilter = TypedEventFilter<ClaimRewardsEvent>;

export interface MoveStakedLiquidityEventObject {
  tokenId: BigNumber;
  fromIndexes: BigNumber[];
  toIndexes: BigNumber[];
}
export type MoveStakedLiquidityEvent = TypedEvent<
  [BigNumber, BigNumber[], BigNumber[]],
  MoveStakedLiquidityEventObject
>;

export type MoveStakedLiquidityEventFilter = TypedEventFilter<MoveStakedLiquidityEvent>;

export interface StakeEventObject {
  owner: string;
  ajnaPool: string;
  tokenId: BigNumber;
}
export type StakeEvent = TypedEvent<[string, string, BigNumber], StakeEventObject>;

export type StakeEventFilter = TypedEventFilter<StakeEvent>;

export interface UnstakeEventObject {
  owner: string;
  ajnaPool: string;
  tokenId: BigNumber;
}
export type UnstakeEvent = TypedEvent<[string, string, BigNumber], UnstakeEventObject>;

export type UnstakeEventFilter = TypedEventFilter<UnstakeEvent>;

export interface UpdateExchangeRatesEventObject {
  caller: string;
  ajnaPool: string;
  indexesUpdated: BigNumber[];
  rewardsClaimed: BigNumber;
}
export type UpdateExchangeRatesEvent = TypedEvent<
  [string, string, BigNumber[], BigNumber],
  UpdateExchangeRatesEventObject
>;

export type UpdateExchangeRatesEventFilter = TypedEventFilter<UpdateExchangeRatesEvent>;

export interface RewardsManager extends BaseContract {
  contractName: 'RewardsManager';

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RewardsManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ajnaToken(overrides?: CallOverrides): Promise<[string]>;

    calculateRewards(
      tokenId_: BigNumberish,
      epochToClaim_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rewards_: BigNumber }>;

    claimRewards(
      tokenId_: BigNumberish,
      epochToClaim_: BigNumberish,
      minAmount_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    emergencyUnstake(
      tokenId_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getBucketStateStakeInfo(
      tokenId_: BigNumberish,
      bucketId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getStakeInfo(
      tokenId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber]>;

    isBucketUpdated(
      pool_: string,
      bucketIndex_: BigNumberish,
      epoch_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isEpochClaimed(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    positionManager(overrides?: CallOverrides): Promise<[string]>;

    rewardsClaimed(arg0: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    stake(
      tokenId_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    unstake(
      tokenId_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateBucketExchangeRatesAndClaim(
      pool_: string,
      subsetHash_: BytesLike,
      indexes_: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateRewardsClaimed(arg0: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  ajnaToken(overrides?: CallOverrides): Promise<string>;

  calculateRewards(
    tokenId_: BigNumberish,
    epochToClaim_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimRewards(
    tokenId_: BigNumberish,
    epochToClaim_: BigNumberish,
    minAmount_: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  emergencyUnstake(
    tokenId_: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getBucketStateStakeInfo(
    tokenId_: BigNumberish,
    bucketId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getStakeInfo(
    tokenId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber]>;

  isBucketUpdated(
    pool_: string,
    bucketIndex_: BigNumberish,
    epoch_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isEpochClaimed(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  positionManager(overrides?: CallOverrides): Promise<string>;

  rewardsClaimed(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  stake(
    tokenId_: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  unstake(
    tokenId_: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateBucketExchangeRatesAndClaim(
    pool_: string,
    subsetHash_: BytesLike,
    indexes_: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateRewardsClaimed(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    ajnaToken(overrides?: CallOverrides): Promise<string>;

    calculateRewards(
      tokenId_: BigNumberish,
      epochToClaim_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimRewards(
      tokenId_: BigNumberish,
      epochToClaim_: BigNumberish,
      minAmount_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    emergencyUnstake(tokenId_: BigNumberish, overrides?: CallOverrides): Promise<void>;

    getBucketStateStakeInfo(
      tokenId_: BigNumberish,
      bucketId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getStakeInfo(
      tokenId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber]>;

    isBucketUpdated(
      pool_: string,
      bucketIndex_: BigNumberish,
      epoch_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isEpochClaimed(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    positionManager(overrides?: CallOverrides): Promise<string>;

    rewardsClaimed(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    stake(tokenId_: BigNumberish, overrides?: CallOverrides): Promise<void>;

    unstake(tokenId_: BigNumberish, overrides?: CallOverrides): Promise<void>;

    updateBucketExchangeRatesAndClaim(
      pool_: string,
      subsetHash_: BytesLike,
      indexes_: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateRewardsClaimed(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    'ClaimRewards(address,address,uint256,uint256[],uint256)'(
      owner?: string | null,
      ajnaPool?: string | null,
      tokenId?: BigNumberish | null,
      epochsClaimed?: null,
      amount?: null
    ): ClaimRewardsEventFilter;
    ClaimRewards(
      owner?: string | null,
      ajnaPool?: string | null,
      tokenId?: BigNumberish | null,
      epochsClaimed?: null,
      amount?: null
    ): ClaimRewardsEventFilter;

    'MoveStakedLiquidity(uint256,uint256[],uint256[])'(
      tokenId?: null,
      fromIndexes?: null,
      toIndexes?: null
    ): MoveStakedLiquidityEventFilter;
    MoveStakedLiquidity(
      tokenId?: null,
      fromIndexes?: null,
      toIndexes?: null
    ): MoveStakedLiquidityEventFilter;

    'Stake(address,address,uint256)'(
      owner?: string | null,
      ajnaPool?: string | null,
      tokenId?: BigNumberish | null
    ): StakeEventFilter;
    Stake(
      owner?: string | null,
      ajnaPool?: string | null,
      tokenId?: BigNumberish | null
    ): StakeEventFilter;

    'Unstake(address,address,uint256)'(
      owner?: string | null,
      ajnaPool?: string | null,
      tokenId?: BigNumberish | null
    ): UnstakeEventFilter;
    Unstake(
      owner?: string | null,
      ajnaPool?: string | null,
      tokenId?: BigNumberish | null
    ): UnstakeEventFilter;

    'UpdateExchangeRates(address,address,uint256[],uint256)'(
      caller?: string | null,
      ajnaPool?: string | null,
      indexesUpdated?: null,
      rewardsClaimed?: null
    ): UpdateExchangeRatesEventFilter;
    UpdateExchangeRates(
      caller?: string | null,
      ajnaPool?: string | null,
      indexesUpdated?: null,
      rewardsClaimed?: null
    ): UpdateExchangeRatesEventFilter;
  };

  estimateGas: {
    ajnaToken(overrides?: CallOverrides): Promise<BigNumber>;

    calculateRewards(
      tokenId_: BigNumberish,
      epochToClaim_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimRewards(
      tokenId_: BigNumberish,
      epochToClaim_: BigNumberish,
      minAmount_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    emergencyUnstake(
      tokenId_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getBucketStateStakeInfo(
      tokenId_: BigNumberish,
      bucketId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStakeInfo(tokenId_: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    isBucketUpdated(
      pool_: string,
      bucketIndex_: BigNumberish,
      epoch_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isEpochClaimed(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    positionManager(overrides?: CallOverrides): Promise<BigNumber>;

    rewardsClaimed(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    stake(tokenId_: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    unstake(tokenId_: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    updateBucketExchangeRatesAndClaim(
      pool_: string,
      subsetHash_: BytesLike,
      indexes_: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateRewardsClaimed(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ajnaToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculateRewards(
      tokenId_: BigNumberish,
      epochToClaim_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimRewards(
      tokenId_: BigNumberish,
      epochToClaim_: BigNumberish,
      minAmount_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    emergencyUnstake(
      tokenId_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getBucketStateStakeInfo(
      tokenId_: BigNumberish,
      bucketId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStakeInfo(tokenId_: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isBucketUpdated(
      pool_: string,
      bucketIndex_: BigNumberish,
      epoch_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isEpochClaimed(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    positionManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rewardsClaimed(arg0: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stake(
      tokenId_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    unstake(
      tokenId_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateBucketExchangeRatesAndClaim(
      pool_: string,
      subsetHash_: BytesLike,
      indexes_: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateRewardsClaimed(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
